[tool.poetry]
name = "testproject"
version = "0.1.0"
description = "testProject using crewAI"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
crewai = { extras = ["tools"], version = ">=0.55.2,<1.0.0" }


[tool.poetry.scripts]
testproject = "testproject.main:run"
run_crew = "testproject.main:run"
train = "testproject.main:train"
replay = "testproject.main:replay"
test = "testproject.main:test"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
