#输入的视频文件
input: D:\Videos\Materials\wealth\The-Shocking-Reason-Why-Some-Countries-Will-Never-Be-Wealthy.mp4
#中间过程会生成的音频文件
output: D:\Videos\Materials\wealth\The-Shocking-Reason-Why-Some-Countries-Will-Never-Be-Wealthy.mp3
#生成的原始字幕文件
srt_path: D:\Videos\Materials\wealth\The-Shocking-Reason-Why-Some-Countries-Will-Never-Be-Wealthy.srt
#生成的翻译后的字幕文件
srt_translate_path: D:\Videos\Materials\wealth\The-Shocking-Reason-Why-Some-Countries-Will-Never-Be-Wealthy-zh.srt
#翻译时开启多少线程
translate_threads: 10
#翻译源语言
from: en
#翻译目标语言
to: zh
#huggingface model地址，例如 D:\download\pytorch_model.bin
hf_model_path: ""
#devive: cuda, cpu
device: cuda
